server-phoenix/lib/helios_web/router.ex
defmodule HeliosWeb.Router do
  use HeliosWeb, :router

  import HeliosWeb.AdminAuth

  pipeline :requires_auth do
    plug HeliosWeb.Plugs.UserAuthentication
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {HeliosWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_admin
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/admin", HeliosWeb.Admin, as: :admin do
    pipe_through [:browser, :require_authenticated_admin]
    resources "/users", UserController
    resources "/developer_users", DeveloperUserController
    resources "/locations", LocationController
    resources "/events", EventController
    resources "/daily_event_summaries", DailyEventSummaryController
    resources "/announcements", AnnouncementController
    resources "/widgets", WidgetController
    resources "/traffic_cams", TrafficCamController
  end

  ## Authentication routes

  scope "/", HeliosWeb do
    pipe_through [:browser, :redirect_if_admin_is_authenticated]

    get "/admins/log_in", AdminSessionController, :new
    post "/admins/log_in", AdminSessionController, :create
    get "/admins/reset_password", AdminResetPasswordController, :new
    post "/admins/reset_password", AdminResetPasswordController, :create
    get "/admins/reset_password/:token", AdminResetPasswordController, :edit
    put "/admins/reset_password/:token", AdminResetPasswordController, :update
  end

  scope "/", HeliosWeb do
    pipe_through [:browser, :require_authenticated_admin]

    get "/admins/settings", AdminSettingsController, :edit
    put "/admins/settings", AdminSettingsController, :update
    get "/admins/settings/confirm_email/:token", AdminSettingsController, :confirm_email
  end

  scope "/", HeliosWeb do
    pipe_through [:browser]

    get "/images/:uuid", SignedImageController, :handle
    delete "/admins/log_out", AdminSessionController, :delete
    get "/admins/confirm", AdminConfirmationController, :new
    post "/admins/confirm", AdminConfirmationController, :create
    get "/admins/confirm/:token", AdminConfirmationController, :edit
    post "/admins/confirm/:token", AdminConfirmationController, :update
  end

  scope "/" do
    pipe_through(:api)
    forward "/graphql", Absinthe.Plug, schema: HeliosWeb.Schema

    forward("/graphiql", Absinthe.Plug.GraphiQL,
      schema: HeliosWeb.Schema,
      socket: HeliosWeb.AbsintheSocketDecorator
    )
  end

  scope "/web_hooks", HeliosWeb.WebHooks do
    post("/github", GithubController, :handle)
    post("/slack", SlackController, :handle)
    post("/publish", PublishController, :handle)
  end

  scope "/api/v:version/events", HeliosWeb.EventsAPI do
    pipe_through(:requires_auth)
    post("/", EventsAPIController, :handle)
  end

  # Other scopes may use custom stacks.
  # scope "/api", HeliosWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: HeliosWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  scope "/auth/google/callback", HeliosWeb do
    pipe_through :browser
    get("/", GoogleAuthController, :index)
  end

  scope "/", HeliosWeb do
    pipe_through :browser
    get("/*path", PageController, :index)
  end
end

server-phoenix/lib/helios_web/views/layout_view.ex
defmodule HeliosWeb.LayoutView do
  use HeliosWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

server-phoenix/lib/helios_web/templates/layout/_admin_menu.html.heex
<ul>
<%= if @current_admin do %>
  <li><%= @current_admin.email %></li>
  <li><%= link "Settings", to: Routes.admin_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.admin_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Log in", to: Routes.admin_session_path(@conn, :new) %></li>
<% end %>
</ul>

server-phoenix/lib/helios_web/templates/layout/_admin_user_menu.html.heex
<ul>
<%= if @current_admin_user do %>
  <li><%= @current_admin_user.email %></li>
  <li><%= link "Log out", to: Routes.admin_user_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Log in", to: Routes.admin_user_session_path(@conn, :new) %></li>
<% end %>
</ul>

server-phoenix/lib/helios_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

server-phoenix/lib/helios_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

server-phoenix/lib/helios_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Helios", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
            <li><%= link "Torch", to: Routes.admin_event_path(@conn, :index) %></li>
          </ul>
          <%= render "_admin_menu.html", assigns %>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src={Routes.static_path(@conn, "/images/phoenix.png")} alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

server-phoenix/lib/helios_web/templates/layout/torch.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <title>Admin</title>
    <!-- Uncomment to just use the bare bones torch styles rather than the theme -->
    <!--<link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/torch/base.css")}>-->
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/torch/theme.css")}>
  </head>

  <body class={Torch.PageView.body_classes(@conn)}>
    <header>
      <section id="torch-account-info">
        <div class="torch-container">
          <a href="/admins/settings"><%= @current_admin.email %></a>
          <a href="/admins/log_out">Logout</a>
        </div>
      </section>

      <section id="torch-nav">
        <div class="torch-container">
          <div class="torch-logo">
            <a href="/">
              <h3>Torch</h3>
            </a>
          </div>
          <nav class="torch-nav">
            <!-- nav links here -->
            <a href="/admin/events">Events</a>
            <a href="/admin/daily_event_summaries">Daily Event Summaries</a>
            <a href="/admin/developer_users">Developer Users</a>
            <a href="/admin/locations">Locations</a>
            <a href="/admin/users">Users</a>
            <a href="/admin/announcements">Announcements</a>
            <a href="/admin/widgets">Widgets</a>
            <a href="/admin/traffic_cams">Traffic Cams</a>
          </nav>
        </div>
      </section>
    </header>

    <%= Torch.FlashView.render("_flash_messages.html", assigns) %>
    <%= @inner_content %>
    <script defer src={Routes.static_path(@conn, "/torch/torch.js")}></script>
  </body>
</html>